[package]
name = "json-api"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
reqwest = { version = "0.11.20", features = [ "json" ], default-features = false }
serde = { version = "1.0.163", features = [ "derive" ] }
serde_json = "1.0.104"
thiserror = "1.0.47"
url = { version = "2.3.1", features = [ "serde" ] }

[dev-dependencies]
tokio = { version = "1.29.1", features = [ "macros" ] }

[features]
default = [ "rustls-tls" ]
native-tls = [ "reqwest/native-tls" ]
rustls-tls = [ "reqwest/rustls-tls" ]
