[package]
name = "json-api"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
reqwest = { version = "0.11.23", features = [ "json" ], default-features = false }
serde = { version = "1.0.195", features = [ "derive" ] }
serde_json = "1.0.109"
thiserror = "1.0.53"
url = { version = "2.5.0", features = [ "serde" ] }

[dev-dependencies]
tokio = { version = "1.35.1", features = [ "macros" ] }

[features]
default = [ "rustls-tls" ]
native-tls = [ "reqwest/native-tls" ]
rustls-tls = [ "reqwest/rustls-tls" ]
