[package]
name = "json_api"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = [ "json" ] }
serde = { version = "1.0.110", features = [ "derive" ] }
serde_json = "1.0.53"
url = { version = "2.1.1", features = [ "serde" ] }

[dev-dependencies]
tokio = { version = "0.2.21", features = [ "macros" ] }
