[package]
name = "json-api"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
reqwest = { version = "0.12.5", features = [ "json" ], default-features = false }
serde = { version = "1.0.206", features = [ "derive" ] }
serde_json = "1.0.124"
thiserror = "1.0.63"
url = { version = "2.5.2", features = [ "serde" ] }

[dev-dependencies]
tokio = { version = "1.39.2", features = [ "macros" ] }

[features]
default = [ "rustls-tls" ]
native-tls = [ "reqwest/native-tls" ]
rustls-tls = [ "reqwest/rustls-tls" ]
