[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-unknown-linux-gnu" },
]

[advisories]
ignore = []

[licenses]
confidence-threshold = 0.93
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "BSD-3-Clause", "Unicode-DFS-2016", "MPL-2.0", "ISC", "OpenSSL", "Unicode-3.0" ]
exceptions = []

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = []
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = []
